### ISSUE TITLE
What is Weka version

### ISSUE THREAD

**Issue by riadh-elloumi** [arrigonialberto86/ruby-band#5]
Hi

How can I know which version of Weka is installed/used ? Can I update the jar file?

Best regards

Riadh

**Comment by arrigonialberto86** [comment]
The currently supported Weka version is
jar 'nz.ac.waikato.cms.weka:weka-stable','3.6.10'
which is downloaded by jbundler when you first require the gem.
You can change this by modifying the Jarfile list in the base directory of the project.
All the jar files are downloaded directly from Maven repositories (I went for the stable version , but you can experiment if you'd like)
