### ISSUE TITLE
Bundler dependency conflicts: bundler (~> 1.3.5) vs. current version bundler (1.5.2)

### ISSUE THREAD

**Issue by paulgoetze** [arrigonialberto86/ruby-band#6]
Using jruby 1.7.10 with rvm 1.25.15 I get this message when running bundle install:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    ruby-band (>= 0) java depends on
      bundler (~> 1.3.5) java

  Current Bundler version:
    bundler (1.5.2)
```

My Gemfile comprises only the `ruby-band` gem.

**Comment by arrigonialberto86** [comment]
Thank your for letting me know :D
I revised the Gemfile and released a patch for that! It passes on Travis, hope it will work for you too

**Comment by paulgoetze** [comment]
It works now. Thank you!
